name: "Build HTML output"
on:
- push

jobs:
  html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python environment
        uses: actions/setup-python@v6
        with: 
          python-version: 3.10
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          if [ -f build-requirements.txt ]; then pip install -r build-requirements.txt; fi
      - name: Build HTML
        uses: rickstaa/sphinx-action@master
        with:
          docs-folder: "."
      - uses: actions/upload-artifact@v6
        with:
          name: ShapingDocumentsHTML
          path: docs/_build/html/
